services:
    postgres:
        restart: unless-stopped
        image: postgres:16-alpine
        environment:
            POSTGRES_DB: codejam
            POSTGRES_PASSWORD: codejam
            POSTGRES_USER: codejam
    bot:
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        environment:
            DATABASE_DSN: postgres://codejam:codejam@postgres:5432/codejam
        depends_on:
            - postgres
