-- UP

CREATE TABLE message (
    id SERIAL PRIMARY KEY,
    userId INT NOT NULL,
    content VARCHAR(500) NOT NULL,
    link VARCHAR(100) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- DOWN

DROP TABLE message;
