-- UP

CREATE TABLE message (
    id SERIAL PRIMARY KEY,
    userid BIGINT NOT NULL,
    content VARCHAR(500) NOT NULL,
    link VARCHAR(100) NOT NULL,
    createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- DOWN

DROP TABLE message;
