# GitHub Action workflow enforcing our code style.
name: linting and type checking

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency: lint-${{ github.sha }}

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: "3.12"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        run: pip install uv

      - name: Create and use virtual environment
        run: |
          uv venv
          echo "${{ github.workspace }}/.venv/bin" >> $GITHUB_PATH

      - name: Install dependencies with uv
        run: |
          uv pip install pre-commit
          uv pip install -r requirements.txt
          uv pip install types-all

      - name: Run pre-commit hooks
        run: pre-commit run --all-files
        env:
          SKIP: no-commit-to-branch
